spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public
        format_sql: true
    show-sql: true

  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/citronix_db
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
server:
  port: 8081
