spring:
  application:
    name: citronix

  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/citronix_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

# Liquibase Configuration
